spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: kilow
  datasource:
    url: jdbc:sqlite:kilow_db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
api:
  security:
    token:
      secret: ${JWT_SECRET:hoje-e-domingo-pe-de-cachimbo}
  scrape:
    token: ${SCRAPE_TOKEN}
  gemini:
    key: ${GEMINI_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=